import log from './log';
import request from './request';
import { getNpmRegistry, getNpmInfo, getLatestVersion, getNpmLatestSemverVersion } from './npm';
import inquirer from './inquirer';
import spinner from './spinner';
import formatPath from './formatPath';
import Package from './Package';
declare function sleep(timeout: number): Promise<void>;
declare function exec(command: string, args: string[], options?: object): ReturnType<typeof import('child_process').spawn>;
export { log, request, getNpmRegistry, getNpmInfo, getLatestVersion, getNpmLatestSemverVersion, inquirer, spinner, Package, sleep, exec, formatPath };
